### ISSUE TITLE
Chapter problems on Bato.to

### ISSUE THREAD

**Issue by rjbs91** [AllMangasReader-dev/AMR#130]
Hi. I've been using this app for a long time (used a fork until now), but 1.5.8.2 seems to have problems detecting chapters from Bato.to.
If I subscribe to a new series, AMR gets stuck on "No chapters found yet...", and if there are new chapters, AMR doesn't detect them (I only noticed this in series that have different translators). Other than that, AMR seems to work.

**Comment by DakuTree** [comment]
For the "No chapters found yet...", try logging in and see if the issue resolves itself.

As for the translator issue, have you got an example link? Don't see how that could be happening..

**Comment by rjbs91** [comment]
I am logged in, and it still says "No chapters found yet...".

http://bato.to/comic/_/comics/silver-spoon-r496
AMR detects 113 chapters, but a new one was released by a new translator and AMR doesn't see it.

I also noticed that all the series that I'm following on Bato.to have a ? instead of the Bato.to icon.

**Comment by braiam** [comment]
Can you export your manga list?

**Comment by rjbs91** [comment]
https://www.dropbox.com/s/9z4clszeurkzyuy/2016-01-29.txt?dl=0

**Comment by rjbs91** [comment]
Just to let you know, I can't receive any updates from Bato.to.

**Comment by DakuTree** [comment]
Done a bit of testing and it seems to be irregular if chapter loading works or not.
Looks like it's some kind of bot detection to too many URLs being loaded so quickly.

Could you try enabling "Save bandwidth while loading chapter list" under Options > All Mangas Reader, and see if series update?

**Comment by rjbs91** [comment]
Nope. Still doesn't work. I also found that AMR doesn't load on https on Bato.to, could that be the cause of the issue?

**Comment by DakuTree** [comment]
https shouldn't cause the chapter list to not work.

I've done a pull request over at https://github.com/AllMangasReader-dev/mirrors/pull/12 which should resolve the issues you're having. Introduced a simple delay before it checks the list which should help avoid the bot detection (at the very least, it's working with the list you linked), also added bato.to https support.

**Comment by rjbs91** [comment]
Thanks for the help. Now I'll just have to wait until @braiam merges your pull request right?

**Comment by DakuTree** [comment]
Yeah.

**Comment by rjbs91** [comment]
I updated AMR to the newest commit, refreshed everything (website implementation, maga lists and chapters lists), and for some reason the mirrors don't appear to be updating. Do I have to do something to update them?

**Comment by DakuTree** [comment]
It "should" update automatically. You could try backing up your list,
uninstalling > reinstalling the ext & reimporting your list and see if
anything changes.

**Comment by rjbs91** [comment]
It worked (I don't know why I didn't try that). Thanks.

**Comment by braiam** [comment]
So, I presume this is fixed, right? Next time a problem arise with a specific mirror can we take to the AllMangasReader-dev/mirrors?
