### ISSUE TITLE
Can't find mirrors

### ISSUE THREAD

**Issue by haidbz** [AllMangasReader-dev/AMR#142]
I get this error in the console for every site when opening the lab (just picked the bottom most for convenience):
```
https://ssl10.ovh.net/~allmanga/community/latest_v2/WhuaMangas.js Failed to load resource: the server responded with a status of 404 (Not Found)
mgEntry.js:491 Script Whua! Mangás failed to be loaded...
mgEntry.js:492 Object
```

Seems as if `https://ssl10.ovh.net/~allmanga/community/` and all things within is no longer hosted, which cripples AMR since that's where the js for all the mirrors are.

**Comment by haidbz** [comment]
Thanks, but now I get a new error. I have now also figured out that the errors appear in the background page's console. So here's the bottom of my console output:

```
jquery.js:4 Refused to load the script 'https://ssl10.ovh.net/~allmanga/community/latest_v2/WhuaMangas.js' because it violates the following Content Security Policy directive: "script-src 'self' https://ssl.google-analytics.com https://community.allmangasreader.com/ https://www.google.com/ https://platform.twitter.com/ https://www.facebook.com/ https://raw.github.com/".
send @ jquery.js:4
mgEntry.js:491 Script Whua! Mangás failed to be loaded...
mgEntry.js:492 Object
background.js:1913 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.initManifestVars @ background.js:1913
background.js:314 synchronization started
background.js:1629 Refreshing chapters at Thu Oct 27 2016 10:05:10 GMT+0200 (Central Europe Daylight Time)
background.js:1664 Next time to refresh chapters list : 1800000
background.js:341 Next time to refresh manga list : 31278184
background.js:355 Next time to refresh websites : 31278213
```

Now, everything between `mgEntry.js:492 Object` and `background.js:...` is not an error, but a warning, but I figured you might want to be made aware of it.
Now, this error is confusing to me, since you already have removed any reference to `https://ssl10.ovh.net/~allmanga/community/latest_v2/`, and I have verified that my local files are up to date, so I have no idea where the reference to that in the error comes from.

**Comment by braiam** [comment]
@haidbz probably cache invalidation. it should fix itself after a while.

**Comment by haidbz** [comment]
Alright, I'll try wait and see for a while, it has most certainly not fixed itself yet.

**Comment by haidbz** [comment]
Well, I have waited quite a while now, still no change... What does `Refused to load the script [...] because it violates the following Content Security Policy directive: [...]` tell you, if anything?

**Comment by stardisblue** [comment]
uninstall and reinstall the extension, just backup your data before 😄

**Comment by haidbz** [comment]
Thanks, that worked! Haa, I really thought I had already done that, though...
